name: Publish linux executables

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build and publish binaries
        run: npm run build-linux
