name: Publish executables

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:

  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build and publish binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CODESIGN_P12_URL }}
          CSC_PASSWORD: ${{ secrets.CODESIGN_P12_PASSWORD }}
        run: npm run build-${{ matrix.name }}
